### ISSUE TITLE
Plugin resetting to default UI on PC restart, `Hub` options not staying

### ISSUE THREAD

**Issue by nickyGyul** [melkypie/resource-packs#217]
Several users are reporting that their Hub pack options are not working. That the plugin resets to the default pack every time their client restarts or their PC restarts. I'm not sure if it's RuneLite profiles causing the issue or something else. 

I've had one user said that their pack stays if they use the pack in the custom path, and another who said that using the pack as a custom pack doesn't work either. Personally I was not able to replicate the issue.

First report of this behaviour was on September 21, 2023

**Comment by PattyRich** [comment]
+1

**Comment by AnxiousRunes** [comment]
+1

**Comment by raiyni** [comment]
I believe this was fixed with ed6af0efa1c96591cc4c99bf1878b3d1611110c9, will reopen if not

**Comment by keywok** [comment]
Still happens when swapping between RuneLite profiles. Have to toggle the plugin off and on to get the pack to re-apply. Also happens on some client restarts.

**Comment by raiyni** [comment]
I haven't pushed that to hub yet

**Comment by raiyni** [comment]
c4320225748365d02c47db49814f3a65cf64f348 closes this for real real I think

**Comment by raiyni** [comment]
I experienced this after the game update today, reopening.

**Comment by raiyni** [comment]
Third times the charm https://github.com/melkypie/resource-packs/commit/708d691baa48a78e9c50f6e231250acb73961132

I tested it with the updated this morning
